// Curated openings + deep branch variations for the Opening Trainer.
// Each "Opening" entry is a single concrete line; many openings have several
// variation entries (e.g. Italian: Giuoco Piano, Italian: Evans Gambit, ...)
// so the existing picker UI scales without any refactor.

export type OpeningMove = {
  san: string;
  side: "w" | "b";
  idea: string; // short coach hint (fallback if AI fails)
};

export type Opening = {
  id: string;
  name: string;
  side: "white" | "black";
  level: "Beginner" | "Intermediate" | "Advanced";
  summary: string;
  moves: OpeningMove[];
};

export const OPENINGS: Opening[] = [
  // ============================================================
  // BEGINNER
  // ============================================================
  {
    id: "italian-giuoco-piano",
    name: "Italian Game: Giuoco Piano",
    side: "white",
    level: "Beginner",
    summary: "Classical 'Quiet Game' — Bc4, c3, d4 building a strong centre.",
    moves: [
      { san: "e4", side: "w", idea: "Centre + open diagonals for Bishop & Queen." },
      { san: "e5", side: "b", idea: "Symmetric central claim." },
      { san: "Nf3", side: "w", idea: "Develop + attack e5." },
      { san: "Nc6", side: "b", idea: "Defend e5, develop." },
      { san: "Bc4", side: "w", idea: "Bishop targets f7 — signature Italian move." },
      { san: "Bc5", side: "b", idea: "Mirror — pressure on f2." },
      { san: "c3", side: "w", idea: "Prepares d4 break, builds big centre." },
      { san: "Nf6", side: "b", idea: "Develop + hit e4." },
      { san: "d4", side: "w", idea: "Central break — Giuoco Piano main line." },
      { san: "exd4", side: "b", idea: "Capture to release tension." },
      { san: "cxd4", side: "w", idea: "Recapture with pawn — strong centre." },
      { san: "Bb4+", side: "b", idea: "Check that disrupts development." },
    ],
  },
  {
    id: "italian-evans-gambit",
    name: "Italian Game: Evans Gambit",
    side: "white",
    level: "Beginner",
    summary: "Aggressive pawn sacrifice — b4!? gains tempo and a huge centre.",
    moves: [
      { san: "e4", side: "w", idea: "King-pawn opening." },
      { san: "e5", side: "b", idea: "Classical reply." },
      { san: "Nf3", side: "w", idea: "Develop." },
      { san: "Nc6", side: "b", idea: "Defend." },
      { san: "Bc4", side: "w", idea: "Italian setup." },
      { san: "Bc5", side: "b", idea: "Mirror." },
      { san: "b4", side: "w", idea: "Evans Gambit — sacrifice b-pawn for tempo + centre." },
      { san: "Bxb4", side: "b", idea: "Accept the pawn (declining is also playable)." },
      { san: "c3", side: "w", idea: "Kick the bishop with tempo, prep d4." },
      { san: "Ba5", side: "b", idea: "Bishop retreats keeping the pin idea." },
      { san: "d4", side: "w", idea: "Now build the dream centre with extra tempo." },
    ],
  },
  {
    id: "london",
    name: "London System",
    side: "white",
    level: "Beginner",
    summary: "Solid d4 system — Bf4, e3, Nf3, c3. Easy to learn, hard to crack.",
    moves: [
      { san: "d4", side: "w", idea: "Queen-pawn centre." },
      { san: "d5", side: "b", idea: "Symmetric." },
      { san: "Nf3", side: "w", idea: "Develop + e5 control." },
      { san: "Nf6", side: "b", idea: "Mirror." },
      { san: "Bf4", side: "w", idea: "Bishop OUT of the pawn chain — London's soul." },
      { san: "e6", side: "b", idea: "Open the bishop." },
      { san: "e3", side: "w", idea: "Solid pawn chain." },
      { san: "Bd6", side: "b", idea: "Challenge the bishop swap." },
      { san: "Bg3", side: "w", idea: "Avoid swap, keep the strong piece." },
    ],
  },
  {
    id: "four-knights",
    name: "Four Knights Game",
    side: "white",
    level: "Beginner",
    summary: "Symmetric, principled development — both sides develop all knights first.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "e5", side: "b", idea: "Mirror." },
      { san: "Nf3", side: "w", idea: "Develop + attack e5." },
      { san: "Nc6", side: "b", idea: "Defend." },
      { san: "Nc3", side: "w", idea: "Develop the second knight — Four Knights." },
      { san: "Nf6", side: "b", idea: "Mirror, hit e4." },
      { san: "Bb5", side: "w", idea: "Spanish-style pin on c6." },
      { san: "Bb4", side: "b", idea: "Mirror pin on c3." },
      { san: "O-O", side: "w", idea: "King safety first." },
    ],
  },

  // ============================================================
  // INTERMEDIATE
  // ============================================================
  {
    id: "caro-advance",
    name: "Caro-Kann: Advance Variation",
    side: "white",
    level: "Intermediate",
    summary: "White grabs space with e5; Black plays …Bf5 then …e6 fortifying.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "c6", side: "b", idea: "Caro-Kann — prepare …d5 without French bishop." },
      { san: "d4", side: "w", idea: "Big centre." },
      { san: "d5", side: "b", idea: "Strike at the centre." },
      { san: "e5", side: "w", idea: "Advance — gain space, fix Black's structure." },
      { san: "Bf5", side: "b", idea: "Solve the bad bishop FIRST — Caro's main idea." },
      { san: "Nf3", side: "w", idea: "Develop." },
      { san: "e6", side: "b", idea: "Solid pawn chain." },
      { san: "Be2", side: "w", idea: "Modest setup; sometimes c3 + Nbd2 follows." },
    ],
  },
  {
    id: "caro-panov",
    name: "Caro-Kann: Panov-Botvinnik Attack",
    side: "white",
    level: "Intermediate",
    summary: "White accepts an IQP for active piece play and central control.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "c6", side: "b", idea: "Caro." },
      { san: "d4", side: "w", idea: "Big centre." },
      { san: "d5", side: "b", idea: "Strike." },
      { san: "exd5", side: "w", idea: "Exchange — go for IQP play." },
      { san: "cxd5", side: "b", idea: "Recapture." },
      { san: "c4", side: "w", idea: "Panov! Challenge d5 immediately." },
      { san: "Nf6", side: "b", idea: "Develop + defend d5." },
      { san: "Nc3", side: "w", idea: "Pile on d5." },
    ],
  },
  {
    id: "french-tarrasch",
    name: "French Defense: Tarrasch Variation",
    side: "white",
    level: "Intermediate",
    summary: "3.Nd2 — keeps options vs the Winawer pin, plays for c3 + e5 structures.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "e6", side: "b", idea: "French — prep …d5." },
      { san: "d4", side: "w", idea: "Big centre." },
      { san: "d5", side: "b", idea: "Strike." },
      { san: "Nd2", side: "w", idea: "Tarrasch — avoids the …Bb4 pin." },
      { san: "Nf6", side: "b", idea: "Develop, hit e4." },
      { san: "e5", side: "w", idea: "Advance — gain space, lock the centre." },
      { san: "Nfd7", side: "b", idea: "Knight reroutes via b6 or f8." },
      { san: "Bd3", side: "w", idea: "Develop toward the kingside." },
    ],
  },
  {
    id: "french-winawer",
    name: "French Defense: Winawer Variation",
    side: "black",
    level: "Intermediate",
    summary: "3…Bb4 — sharp Winawer, Black accepts doubled pawns for dynamic play.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "e6", side: "b", idea: "French." },
      { san: "d4", side: "w", idea: "Centre." },
      { san: "d5", side: "b", idea: "Strike." },
      { san: "Nc3", side: "w", idea: "Develop, defend e4." },
      { san: "Bb4", side: "b", idea: "Winawer pin on c3 knight." },
      { san: "e5", side: "w", idea: "Advance — lock centre, gain kingside space." },
      { san: "c5", side: "b", idea: "Counter in centre immediately." },
      { san: "a3", side: "w", idea: "Force the trade Bxc3+." },
      { san: "Bxc3+", side: "b", idea: "Doubled pawns for White — Black's long-term target." },
    ],
  },
  {
    id: "sicilian-dragon",
    name: "Sicilian: Dragon Variation",
    side: "black",
    level: "Intermediate",
    summary: "Fianchetto setup (…g6, …Bg7) — sharp, opposite-side castling races.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "c5", side: "b", idea: "Sicilian." },
      { san: "Nf3", side: "w", idea: "Develop." },
      { san: "d6", side: "b", idea: "Flexible setup." },
      { san: "d4", side: "w", idea: "Open Sicilian." },
      { san: "cxd4", side: "b", idea: "Open the c-file." },
      { san: "Nxd4", side: "w", idea: "Recapture." },
      { san: "Nf6", side: "b", idea: "Develop, hit e4." },
      { san: "Nc3", side: "w", idea: "Defend e4." },
      { san: "g6", side: "b", idea: "Dragon — prepare the long-diagonal bishop." },
      { san: "Be3", side: "w", idea: "Develop, possible Yugoslav with Qd2 + O-O-O + h4." },
      { san: "Bg7", side: "b", idea: "The 'dragon' bishop — central + queenside power." },
    ],
  },
  {
    id: "sicilian-alapin",
    name: "Sicilian: Alapin (2.c3)",
    side: "white",
    level: "Intermediate",
    summary: "Anti-Sicilian: 2.c3 builds a classical centre with d4.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "c5", side: "b", idea: "Sicilian." },
      { san: "c3", side: "w", idea: "Alapin — prepare d4 with pawns." },
      { san: "d5", side: "b", idea: "Best reply — strike before d4." },
      { san: "exd5", side: "w", idea: "Exchange." },
      { san: "Qxd5", side: "b", idea: "Recapture; queen is exposed though." },
      { san: "d4", side: "w", idea: "Big centre, tempo on queen later with Nc3." },
      { san: "Nc6", side: "b", idea: "Develop." },
      { san: "Nf3", side: "w", idea: "Develop." },
    ],
  },

  // ============================================================
  // ADVANCED
  // ============================================================
  {
    id: "ruy-berlin",
    name: "Ruy López: Berlin Defense",
    side: "black",
    level: "Advanced",
    summary: "Drawing weapon at the top — solid endgame structures after exd5.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "e5", side: "b", idea: "Classical." },
      { san: "Nf3", side: "w", idea: "Develop, attack e5." },
      { san: "Nc6", side: "b", idea: "Defend." },
      { san: "Bb5", side: "w", idea: "Ruy López pin." },
      { san: "Nf6", side: "b", idea: "Berlin — counterattack e4 immediately." },
      { san: "O-O", side: "w", idea: "King safety, sidestep …Nxe4." },
      { san: "Nxe4", side: "b", idea: "Take the pawn — Berlin's idea." },
      { san: "d4", side: "w", idea: "Centre break, target e5." },
      { san: "Nd6", side: "b", idea: "Knight retreats covering b5/c4 attacks." },
      { san: "Bxc6", side: "w", idea: "Forces …dxc6 → famous Berlin endgame structure." },
    ],
  },
  {
    id: "ruy-marshall",
    name: "Ruy López: Marshall Attack",
    side: "black",
    level: "Advanced",
    summary: "Black sacrifices a pawn for a long-term kingside attack.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "e5", side: "b", idea: "Reply." },
      { san: "Nf3", side: "w", idea: "Develop." },
      { san: "Nc6", side: "b", idea: "Defend." },
      { san: "Bb5", side: "w", idea: "Ruy." },
      { san: "a6", side: "b", idea: "Morphy." },
      { san: "Ba4", side: "w", idea: "Maintain pin." },
      { san: "Nf6", side: "b", idea: "Develop." },
      { san: "O-O", side: "w", idea: "Castle." },
      { san: "Be7", side: "b", idea: "Closed Spanish setup." },
      { san: "Re1", side: "w", idea: "Defend e4." },
      { san: "b5", side: "b", idea: "Kick the bishop." },
      { san: "Bb3", side: "w", idea: "Retreat." },
      { san: "O-O", side: "b", idea: "Castle." },
      { san: "c3", side: "w", idea: "Prepare d4." },
      { san: "d5", side: "b", idea: "Marshall! Sacrifice for attack." },
      { san: "exd5", side: "w", idea: "Accept." },
      { san: "Nxd5", side: "b", idea: "Open lines for the attack." },
    ],
  },
  {
    id: "kid-mar-del-plata",
    name: "King's Indian Defense: Mar del Plata",
    side: "black",
    level: "Advanced",
    summary: "Classic KID — White attacks queenside with c5, Black storms kingside with …f5-f4-g5.",
    moves: [
      { san: "d4", side: "w", idea: "Queen-pawn." },
      { san: "Nf6", side: "b", idea: "Flexible, controls e4." },
      { san: "c4", side: "w", idea: "Stake the centre." },
      { san: "g6", side: "b", idea: "KID setup." },
      { san: "Nc3", side: "w", idea: "Develop." },
      { san: "Bg7", side: "b", idea: "Fianchetto." },
      { san: "e4", side: "w", idea: "Classical KID — big centre." },
      { san: "d6", side: "b", idea: "Restrain e5 push, prep …e5." },
      { san: "Nf3", side: "w", idea: "Develop." },
      { san: "O-O", side: "b", idea: "Castle." },
      { san: "Be2", side: "w", idea: "Classical line." },
      { san: "e5", side: "b", idea: "Stake the centre." },
      { san: "d5", side: "w", idea: "Close the centre — sides will attack on opposite wings." },
      { san: "Nbd7", side: "b", idea: "Prepare …Nc5 or …f5 break." },
    ],
  },
  {
    id: "grunfeld",
    name: "Grünfeld Defense",
    side: "black",
    level: "Advanced",
    summary: "Hyper-modern: let White build a big centre, then attack it with pieces.",
    moves: [
      { san: "d4", side: "w", idea: "Centre." },
      { san: "Nf6", side: "b", idea: "Flexible." },
      { san: "c4", side: "w", idea: "Stake centre." },
      { san: "g6", side: "b", idea: "Prep fianchetto." },
      { san: "Nc3", side: "w", idea: "Develop." },
      { san: "d5", side: "b", idea: "Grünfeld! Challenge centre immediately." },
      { san: "cxd5", side: "w", idea: "Exchange." },
      { san: "Nxd5", side: "b", idea: "Recapture with knight (Grünfeld's trademark)." },
      { san: "e4", side: "w", idea: "Kick knight, build huge centre." },
      { san: "Nxc3", side: "b", idea: "Trade — give White doubled c-pawns to attack later." },
      { san: "bxc3", side: "w", idea: "Recapture — accept doubled pawns for centre." },
      { san: "Bg7", side: "b", idea: "Fianchetto — pressure the c3/d4 centre." },
    ],
  },

  // ----- ORIGINAL CORE OPENINGS (kept for continuity) -----
  {
    id: "ruy",
    name: "Ruy López (Main Line)",
    side: "white",
    level: "Intermediate",
    summary: "The 'Spanish Torture' — Bb5 pinning c6 knight, deep strategic play.",
    moves: [
      { san: "e4", side: "w", idea: "King-pawn opening." },
      { san: "e5", side: "b", idea: "Classical." },
      { san: "Nf3", side: "w", idea: "Attack e5." },
      { san: "Nc6", side: "b", idea: "Defend." },
      { san: "Bb5", side: "w", idea: "Pin on c6 — Ruy López." },
      { san: "a6", side: "b", idea: "Morphy Defense." },
      { san: "Ba4", side: "w", idea: "Maintain pin." },
      { san: "Nf6", side: "b", idea: "Develop, hit e4." },
      { san: "O-O", side: "w", idea: "King safety." },
    ],
  },
  {
    id: "caro",
    name: "Caro-Kann (Classical)",
    side: "black",
    level: "Beginner",
    summary: "Solid Caro — exchange and free the c8 bishop with …Bf5.",
    moves: [
      { san: "e4", side: "w", idea: "Centre." },
      { san: "c6", side: "b", idea: "Caro." },
      { san: "d4", side: "w", idea: "Centre." },
      { san: "d5", side: "b", idea: "Strike." },
      { san: "Nc3", side: "w", idea: "Develop + defend e4." },
      { san: "dxe4", side: "b", idea: "Classical Caro." },
      { san: "Nxe4", side: "w", idea: "Recapture." },
      { san: "Bf5", side: "b", idea: "Free the bad bishop — Caro's main idea." },
    ],
  },
  {
    id: "sicilian-najdorf",
    name: "Sicilian: Najdorf",
    side: "black",
    level: "Intermediate",
    summary: "Sharpest reply to e4 — asymmetric, counter-attacking.",
    moves: [
      { san: "e4", side: "w", idea: "King-pawn." },
      { san: "c5", side: "b", idea: "Sicilian." },
      { san: "Nf3", side: "w", idea: "Develop." },
      { san: "d6", side: "b", idea: "Flexible." },
      { san: "d4", side: "w", idea: "Open Sicilian." },
      { san: "cxd4", side: "b", idea: "Capture, open c-file." },
      { san: "Nxd4", side: "w", idea: "Recapture." },
      { san: "Nf6", side: "b", idea: "Develop, hit e4." },
      { san: "Nc3", side: "w", idea: "Defend e4 + develop." },
      { san: "a6", side: "b", idea: "Najdorf — prevent Nb5, prep …b5." },
    ],
  },
];

export function getOpening(id: string): Opening | undefined {
  return OPENINGS.find((o) => o.id === id);
}
