// 25+ curated opening traps. User plays the "trapper" side; opponent moves are scripted.
export type Trap = {
  id: string;
  name: string;
  opening: string;
  side: "white" | "black"; // side the user plays (the trapper)
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  moves: string[]; // full SAN sequence from start
  idea: string;   // one-line summary
  lesson: string; // defensive lesson (how to avoid as the victim)
};

export const TRAPS: Trap[] = [
  // ---------------- BEGINNER ----------------
  {
    id: "scholars-mate",
    name: "Scholar's Mate",
    opening: "Italian / Open Game",
    side: "white",
    difficulty: "Beginner",
    moves: ["e4", "e5", "Bc4", "Nc6", "Qh5", "Nf6", "Qxf7#"],
    idea: "Quick queen + bishop attack on f7, the weakest square in the opening.",
    lesson: "As Black, after 3.Qh5 defend f7 with **g6** or **Qe7/Qf6** — never …Nf6 blocking the defender.",
  },
  {
    id: "englund-gambit",
    name: "Englund Gambit Trap",
    opening: "Englund Gambit",
    side: "black",
    difficulty: "Beginner",
    moves: ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Bc3", "Bb4", "Qd2", "Bxc3", "Qxc3", "Qc1#"],
    idea: "Queen raid down the b-file ends in a smothered back-rank mate on c1.",
    lesson: "As White, after 4.Bf4? Qb4+ the queenside becomes poisoned — play **4.Nc3** instead.",
  },
  {
    id: "london-trap",
    name: "London System Trap",
    opening: "London System",
    side: "white",
    difficulty: "Beginner",
    moves: ["d4", "d5", "Bf4", "Nf6", "e3", "c5", "c3", "Qb6", "Qb3", "Qxb3", "axb3"],
    idea: "Queen trade wrecks Black's structure if they grab b2.",
    lesson: "As Black vs London, do not play **…Qxb2?** — White's Qb3 + Bc7 ideas trap the queen.",
  },
  {
    id: "blackburne-shilling",
    name: "Blackburne–Shilling Gambit",
    opening: "Italian (3…Nd4)",
    side: "black",
    difficulty: "Beginner",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nd4", "Nxe5", "Qg5", "Nxf7", "Qxg2", "Rf1", "Qxe4+", "Be2", "Nf3#"],
    idea: "Greedy White grabs material and gets mated by the bouncing queen + knight.",
    lesson: "As White, after 3…Nd4 don't grab 4.Nxe5? — calmly play **4.Nxd4** or **4.O-O**.",
  },
  {
    id: "stafford-gambit",
    name: "Stafford Gambit Trap",
    opening: "Petroff / Stafford",
    side: "black",
    difficulty: "Beginner",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Bg5", "Nxe4", "Bxd8", "Bxf2+", "Ke2", "Bg4#"],
    idea: "Bishop pair + open lines create a mating net even after queen trade.",
    lesson: "As White, after Stafford do not grab the knight on e4 — play **6.Be2** or **6.Nc3** first.",
  },
  {
    id: "tennison-gambit",
    name: "Tennison Gambit Trap",
    opening: "Tennison Gambit",
    side: "white",
    difficulty: "Beginner",
    moves: ["Nf3", "d5", "e4", "dxe4", "Ng5", "Nf6", "Bc4", "Bf5", "Nxf7", "Kxf7", "Bxf7+", "Kxf7", "Qf3+", "Kg6", "Qxf5+"],
    idea: "Sacrifices unleash the queen and bishop on the exposed king.",
    lesson: "As Black, after 2.e4 prefer **2…Nf6** or **2…e6** instead of grabbing the pawn.",
  },
  {
    id: "rousseau-gambit",
    name: "Rousseau Gambit Trap",
    opening: "Italian (3…f5)",
    side: "white",
    difficulty: "Beginner",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "f5", "d4", "fxe4", "Nxe5", "Nxe5", "dxe5", "exf3", "Qxf3"],
    idea: "Sharp lines punish Black's premature …f5.",
    lesson: "As Black, 3…f5? weakens the king. Stick with **3…Bc5** or **3…Nf6**.",
  },

  // ---------------- INTERMEDIATE ----------------
  {
    id: "legals-mate",
    name: "Légal's Mate",
    opening: "Italian / Philidor",
    side: "white",
    difficulty: "Intermediate",
    moves: ["e4", "e5", "Nf3", "d6", "Bc4", "Bg4", "Nc3", "g6", "Nxe5", "Bxd1", "Bxf7+", "Ke7", "Nd5#"],
    idea: "Queen sacrifice exploits the pinned knight and king in the centre.",
    lesson: "As Black, never pin the f3-knight with …Bg4 when your king is uncastled and f7 is undefended.",
  },
  {
    id: "fried-liver",
    name: "Fried Liver Attack",
    opening: "Italian (Two Knights)",
    side: "white",
    difficulty: "Intermediate",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3"],
    idea: "Sacrifice on f7 drags the king to e6 with a crushing attack.",
    lesson: "As Black, prefer **5…Na5** (Polerio) over 5…Nxd5 to dodge the Fried Liver.",
  },
  {
    id: "noahs-ark",
    name: "Noah's Ark Trap",
    opening: "Ruy Lopez",
    side: "black",
    difficulty: "Intermediate",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "d6", "d4", "b5", "Bb3", "Nxd4", "Nxd4", "exd4", "Qxd4", "c5", "Qd5", "Be6", "Qc6+", "Bd7", "Qd5", "c4"],
    idea: "Pawns a6-b5-c4 trap the white light-squared bishop on b3.",
    lesson: "As White in the Ruy Lopez, play **c3** before allowing …c5-c4.",
  },
  {
    id: "elephant-trap",
    name: "Elephant Trap",
    opening: "Queen's Gambit Declined",
    side: "black",
    difficulty: "Intermediate",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Nbd7", "cxd5", "exd5", "Nxd5", "Nxd5", "Bxd8", "Bb4+", "Qd2", "Bxd2+", "Kxd2", "Kxd8"],
    idea: "Looks like Black loses the queen but Bb4+ wins the bishop on d8 a piece up.",
    lesson: "As White, do not grab on d5 with the knight when Black has the …Bb4+ resource.",
  },
  {
    id: "siberian-trap",
    name: "Siberian Trap",
    opening: "Sicilian Smith-Morra",
    side: "black",
    difficulty: "Intermediate",
    moves: ["e4", "c5", "d4", "cxd4", "c3", "dxc3", "Nxc3", "Nc6", "Nf3", "e6", "Bc4", "Qc7", "O-O", "Nf6", "Qe2", "Ng4", "h3", "Nd4"],
    idea: "Knight jumps to d4 with the queen on c7 — White can't avoid losing the queen on e2 or material to …Nf3+.",
    lesson: "As White in Smith-Morra, beware …Qc7 + …Ng4 patterns — keep the e2-queen out of …Nd4 attacks.",
  },
  {
    id: "fishing-pole",
    name: "Fishing Pole Trap",
    opening: "Ruy Lopez (Berlin-like)",
    side: "black",
    difficulty: "Intermediate",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "O-O", "Ng4", "h3", "h5", "hxg4", "hxg4", "Ne1", "Qh4"],
    idea: "Knight sacrifice opens the h-file with an unstoppable mate attack.",
    lesson: "As White, after …Ng4 do not play **h3** automatically — defend with **Re1** or kick with **d3** instead.",
  },
  {
    id: "cambridge-springs",
    name: "Cambridge Springs Trap",
    opening: "Queen's Gambit Declined",
    side: "black",
    difficulty: "Intermediate",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Nbd7", "Nf3", "c6", "e3", "Qa5", "Nd2", "Bb4", "Qc2", "dxc4", "Bxf6", "Nxf6", "Nxc4", "Qc7"],
    idea: "Pin on c3 + queen on a5 wins material if White is careless.",
    lesson: "As White, vs Cambridge Springs, do not play **Bxf6?** — break the pin with **Rc1** or **a3** first.",
  },
  {
    id: "rubinstein-trap",
    name: "Rubinstein Trap",
    opening: "Queen's Gambit Declined",
    side: "white",
    difficulty: "Intermediate",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Be7", "e3", "Nbd7", "Nf3", "O-O", "Rc1", "c6", "Bd3", "dxc4", "Bxc4", "Nb6", "Bd3", "Nbd7", "O-O", "a6", "a3", "Re8", "Qc2", "Nf8", "Bf4", "Bd6"],
    idea: "Long-known QGD trap — Black's slow play leads to lost material via Nb5 ideas.",
    lesson: "As Black in classical QGD, do not let the c3-knight reach b5 freely — play **…a6** in good time.",
  },
  {
    id: "mortimer-trap",
    name: "Mortimer Trap",
    opening: "Ruy Lopez",
    side: "black",
    difficulty: "Intermediate",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "Ne5", "Ne7", "Nf3", "c6", "Bc4", "d5"],
    idea: "Black's odd retreat sets a trap on the e5 knight; greedy White loses material.",
    lesson: "As White, do not play **4.Ne5?** vs Berlin — play normal moves like **O-O** instead.",
  },
  {
    id: "halosar-trap",
    name: "Halosar Trap",
    opening: "Blackmar-Diemer Gambit",
    side: "white",
    difficulty: "Intermediate",
    moves: ["d4", "d5", "e4", "dxe4", "Nc3", "Nf6", "f3", "exf3", "Qxf3", "Qxd4", "Be3", "Qg4", "Nb5", "Na6", "Qxb7"],
    idea: "Queen race in a gambit position ends with mating threats and material gain.",
    lesson: "As Black vs BDG, do not grab the d4 pawn with the queen — develop calmly with **…e6** or **…Bf5**.",
  },
  {
    id: "wurzburger-trap",
    name: "Würzburger Trap",
    opening: "Vienna Gambit",
    side: "white",
    difficulty: "Intermediate",
    moves: ["e4", "e5", "Nc3", "Nf6", "Bc4", "Nxe4", "Qh5", "Nd6", "Bb3", "Nc6", "Nb5", "g6", "Qf3", "f5", "Qd5"],
    idea: "Black's loose pieces fall to coordinated queen + knight pressure.",
    lesson: "As Black vs Vienna, do not snatch e4 on move 3 — develop with **3…Nc6** first.",
  },
  {
    id: "tarrasch-trap",
    name: "Tarrasch Trap",
    opening: "Ruy Lopez Open",
    side: "white",
    difficulty: "Intermediate",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Nxe4", "d4", "b5", "Bb3", "d5", "dxe5", "Be6", "c3", "Nc5", "Nbd2", "O-O", "Bc2", "Nxe5"],
    idea: "Open Spanish line where Black's greedy …Nxe5 loses to a clean tactical sequence.",
    lesson: "As Black in the Open Ruy, do not grab e5 too soon — keep the knight on c5 supported.",
  },
  {
    id: "kieninger-trap",
    name: "Kieninger Trap",
    opening: "Budapest Gambit",
    side: "black",
    difficulty: "Intermediate",
    moves: ["d4", "Nf6", "c4", "e5", "dxe5", "Ng4", "Bf4", "Nc6", "Nf3", "Bb4+", "Nbd2", "Qe7", "a3", "Ngxe5", "axb4", "Nd3#"],
    idea: "Smothered mate by the Budapest knight on d3.",
    lesson: "As White vs Budapest, do not play **a3** carelessly — first secure the king with **e3** + **Be2**.",
  },

  // ---------------- ADVANCED ----------------
  {
    id: "lasker-trap",
    name: "Lasker Trap",
    opening: "Albin Counter-Gambit",
    side: "black",
    difficulty: "Advanced",
    moves: ["d4", "d5", "c4", "e5", "dxe5", "d4", "e3", "Bb4+", "Bd2", "dxe3", "Bxb4", "exf2+", "Ke2", "fxg1=N+"],
    idea: "Famous underpromotion to a knight winning material.",
    lesson: "As White vs Albin, do NOT play **4.e3?** — the standard line is **4.Nf3**.",
  },
  {
    id: "monticelli-trap",
    name: "Monticelli Trap",
    opening: "Bogo-Indian",
    side: "white",
    difficulty: "Advanced",
    moves: ["d4", "Nf6", "c4", "e6", "Nf3", "Bb4+", "Bd2", "Bxd2+", "Qxd2", "b6", "g3", "Bb7", "Bg2", "O-O", "Nc3", "Ne4", "Qc2", "Nxc3", "Ng5"],
    idea: "Knight sortie wins the b7 bishop via the long diagonal.",
    lesson: "As Black, after Nc3-Ne4 trades, beware **Ng5** uncovering the g2 bishop.",
  },
  {
    id: "magnus-smith",
    name: "Magnus Smith Trap",
    opening: "Sicilian Najdorf-ish",
    side: "white",
    difficulty: "Advanced",
    moves: ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "d6", "Bc4", "g6", "Nxc6", "bxc6", "e5", "Ng4", "Bxf7+", "Kxf7", "Ng5+", "Ke8", "Qxg4"],
    idea: "Bxf7+ followed by Ng5+ wins the knight on g4 with attack.",
    lesson: "As Black in Sicilian, do not play …g6 with the bishop still on c4 aiming at f7.",
  },
  {
    id: "fajarowicz-trap",
    name: "Fajarowicz Trap",
    opening: "Budapest (Fajarowicz)",
    side: "black",
    difficulty: "Advanced",
    moves: ["d4", "Nf6", "c4", "e5", "dxe5", "Ne4", "Nd2", "Nc5", "Ngf3", "Nc6", "a3", "a5", "g3", "Qe7", "Bg2", "Nxe5"],
    idea: "Sharp gambit; Black's active knights threaten dark-square outposts and …Nd3.",
    lesson: "As White vs Fajarowicz, develop classically — do not chase pawns with **f3** or **Qd5**.",
  },
  {
    id: "budapest-trap",
    name: "Budapest Trap (Adler)",
    opening: "Budapest Gambit",
    side: "black",
    difficulty: "Advanced",
    moves: ["d4", "Nf6", "c4", "e5", "dxe5", "Ng4", "Nf3", "Bc5", "e3", "Nc6", "Be2", "Ngxe5", "Nxe5", "Nxe5", "O-O", "d6"],
    idea: "Active piece play in return for the pawn — White must be very accurate.",
    lesson: "As White vs Budapest, return the pawn with **e3 + Be2 + O-O** and complete development.",
  },
];

export function listTraps() { return TRAPS; }
export function getTrap(id: string) { return TRAPS.find((t) => t.id === id); }
