/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrapsRouteImport } from './routes/_authenticated/traps'
import { Route as AuthenticatedTacticsRouteImport } from './routes/_authenticated/tactics'
import { Route as AuthenticatedPuzzlesRouteImport } from './routes/_authenticated/puzzles'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedOpeningsRouteImport } from './routes/_authenticated/openings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMiddlegameRouteImport } from './routes/_authenticated/middlegame'
import { Route as AuthenticatedMasterclassRouteImport } from './routes/_authenticated/masterclass'
import { Route as AuthenticatedLiveTalkRouteImport } from './routes/_authenticated/live-talk'
import { Route as AuthenticatedGmCoachRouteImport } from './routes/_authenticated/gm-coach'
import { Route as AuthenticatedExplorerRouteImport } from './routes/_authenticated/explorer'
import { Route as AuthenticatedEndgameRouteImport } from './routes/_authenticated/endgame'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyPlanRouteImport } from './routes/_authenticated/daily-plan'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedAnalyzeRouteImport } from './routes/_authenticated/analyze'
import { Route as AuthenticatedAcademiesRouteImport } from './routes/_authenticated/academies'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrapsRoute = AuthenticatedTrapsRouteImport.update({
  id: '/traps',
  path: '/traps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTacticsRoute = AuthenticatedTacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPuzzlesRoute = AuthenticatedPuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpeningsRoute = AuthenticatedOpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMiddlegameRoute = AuthenticatedMiddlegameRouteImport.update({
  id: '/middlegame',
  path: '/middlegame',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterclassRoute =
  AuthenticatedMasterclassRouteImport.update({
    id: '/masterclass',
    path: '/masterclass',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLiveTalkRoute = AuthenticatedLiveTalkRouteImport.update({
  id: '/live-talk',
  path: '/live-talk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGmCoachRoute = AuthenticatedGmCoachRouteImport.update({
  id: '/gm-coach',
  path: '/gm-coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExplorerRoute = AuthenticatedExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEndgameRoute = AuthenticatedEndgameRouteImport.update({
  id: '/endgame',
  path: '/endgame',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDailyPlanRoute = AuthenticatedDailyPlanRouteImport.update({
  id: '/daily-plan',
  path: '/daily-plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyzeRoute = AuthenticatedAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcademiesRoute = AuthenticatedAcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academies': typeof AuthenticatedAcademiesRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/daily-plan': typeof AuthenticatedDailyPlanRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/endgame': typeof AuthenticatedEndgameRoute
  '/explorer': typeof AuthenticatedExplorerRoute
  '/gm-coach': typeof AuthenticatedGmCoachRoute
  '/live-talk': typeof AuthenticatedLiveTalkRoute
  '/masterclass': typeof AuthenticatedMasterclassRoute
  '/middlegame': typeof AuthenticatedMiddlegameRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/openings': typeof AuthenticatedOpeningsRoute
  '/play': typeof AuthenticatedPlayRoute
  '/puzzles': typeof AuthenticatedPuzzlesRoute
  '/tactics': typeof AuthenticatedTacticsRoute
  '/traps': typeof AuthenticatedTrapsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academies': typeof AuthenticatedAcademiesRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/daily-plan': typeof AuthenticatedDailyPlanRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/endgame': typeof AuthenticatedEndgameRoute
  '/explorer': typeof AuthenticatedExplorerRoute
  '/gm-coach': typeof AuthenticatedGmCoachRoute
  '/live-talk': typeof AuthenticatedLiveTalkRoute
  '/masterclass': typeof AuthenticatedMasterclassRoute
  '/middlegame': typeof AuthenticatedMiddlegameRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/openings': typeof AuthenticatedOpeningsRoute
  '/play': typeof AuthenticatedPlayRoute
  '/puzzles': typeof AuthenticatedPuzzlesRoute
  '/tactics': typeof AuthenticatedTacticsRoute
  '/traps': typeof AuthenticatedTrapsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/academies': typeof AuthenticatedAcademiesRoute
  '/_authenticated/analyze': typeof AuthenticatedAnalyzeRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/daily-plan': typeof AuthenticatedDailyPlanRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/endgame': typeof AuthenticatedEndgameRoute
  '/_authenticated/explorer': typeof AuthenticatedExplorerRoute
  '/_authenticated/gm-coach': typeof AuthenticatedGmCoachRoute
  '/_authenticated/live-talk': typeof AuthenticatedLiveTalkRoute
  '/_authenticated/masterclass': typeof AuthenticatedMasterclassRoute
  '/_authenticated/middlegame': typeof AuthenticatedMiddlegameRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/openings': typeof AuthenticatedOpeningsRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/puzzles': typeof AuthenticatedPuzzlesRoute
  '/_authenticated/tactics': typeof AuthenticatedTacticsRoute
  '/_authenticated/traps': typeof AuthenticatedTrapsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/academies'
    | '/analyze'
    | '/coach'
    | '/daily-plan'
    | '/dashboard'
    | '/endgame'
    | '/explorer'
    | '/gm-coach'
    | '/live-talk'
    | '/masterclass'
    | '/middlegame'
    | '/onboarding'
    | '/openings'
    | '/play'
    | '/puzzles'
    | '/tactics'
    | '/traps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/academies'
    | '/analyze'
    | '/coach'
    | '/daily-plan'
    | '/dashboard'
    | '/endgame'
    | '/explorer'
    | '/gm-coach'
    | '/live-talk'
    | '/masterclass'
    | '/middlegame'
    | '/onboarding'
    | '/openings'
    | '/play'
    | '/puzzles'
    | '/tactics'
    | '/traps'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/academies'
    | '/_authenticated/analyze'
    | '/_authenticated/coach'
    | '/_authenticated/daily-plan'
    | '/_authenticated/dashboard'
    | '/_authenticated/endgame'
    | '/_authenticated/explorer'
    | '/_authenticated/gm-coach'
    | '/_authenticated/live-talk'
    | '/_authenticated/masterclass'
    | '/_authenticated/middlegame'
    | '/_authenticated/onboarding'
    | '/_authenticated/openings'
    | '/_authenticated/play'
    | '/_authenticated/puzzles'
    | '/_authenticated/tactics'
    | '/_authenticated/traps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/traps': {
      id: '/_authenticated/traps'
      path: '/traps'
      fullPath: '/traps'
      preLoaderRoute: typeof AuthenticatedTrapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tactics': {
      id: '/_authenticated/tactics'
      path: '/tactics'
      fullPath: '/tactics'
      preLoaderRoute: typeof AuthenticatedTacticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/puzzles': {
      id: '/_authenticated/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof AuthenticatedPuzzlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/openings': {
      id: '/_authenticated/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof AuthenticatedOpeningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/middlegame': {
      id: '/_authenticated/middlegame'
      path: '/middlegame'
      fullPath: '/middlegame'
      preLoaderRoute: typeof AuthenticatedMiddlegameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/masterclass': {
      id: '/_authenticated/masterclass'
      path: '/masterclass'
      fullPath: '/masterclass'
      preLoaderRoute: typeof AuthenticatedMasterclassRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live-talk': {
      id: '/_authenticated/live-talk'
      path: '/live-talk'
      fullPath: '/live-talk'
      preLoaderRoute: typeof AuthenticatedLiveTalkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gm-coach': {
      id: '/_authenticated/gm-coach'
      path: '/gm-coach'
      fullPath: '/gm-coach'
      preLoaderRoute: typeof AuthenticatedGmCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explorer': {
      id: '/_authenticated/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AuthenticatedExplorerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/endgame': {
      id: '/_authenticated/endgame'
      path: '/endgame'
      fullPath: '/endgame'
      preLoaderRoute: typeof AuthenticatedEndgameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily-plan': {
      id: '/_authenticated/daily-plan'
      path: '/daily-plan'
      fullPath: '/daily-plan'
      preLoaderRoute: typeof AuthenticatedDailyPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyze': {
      id: '/_authenticated/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthenticatedAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academies': {
      id: '/_authenticated/academies'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AuthenticatedAcademiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAcademiesRoute: typeof AuthenticatedAcademiesRoute
  AuthenticatedAnalyzeRoute: typeof AuthenticatedAnalyzeRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDailyPlanRoute: typeof AuthenticatedDailyPlanRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEndgameRoute: typeof AuthenticatedEndgameRoute
  AuthenticatedExplorerRoute: typeof AuthenticatedExplorerRoute
  AuthenticatedGmCoachRoute: typeof AuthenticatedGmCoachRoute
  AuthenticatedLiveTalkRoute: typeof AuthenticatedLiveTalkRoute
  AuthenticatedMasterclassRoute: typeof AuthenticatedMasterclassRoute
  AuthenticatedMiddlegameRoute: typeof AuthenticatedMiddlegameRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOpeningsRoute: typeof AuthenticatedOpeningsRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedPuzzlesRoute: typeof AuthenticatedPuzzlesRoute
  AuthenticatedTacticsRoute: typeof AuthenticatedTacticsRoute
  AuthenticatedTrapsRoute: typeof AuthenticatedTrapsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcademiesRoute: AuthenticatedAcademiesRoute,
  AuthenticatedAnalyzeRoute: AuthenticatedAnalyzeRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDailyPlanRoute: AuthenticatedDailyPlanRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEndgameRoute: AuthenticatedEndgameRoute,
  AuthenticatedExplorerRoute: AuthenticatedExplorerRoute,
  AuthenticatedGmCoachRoute: AuthenticatedGmCoachRoute,
  AuthenticatedLiveTalkRoute: AuthenticatedLiveTalkRoute,
  AuthenticatedMasterclassRoute: AuthenticatedMasterclassRoute,
  AuthenticatedMiddlegameRoute: AuthenticatedMiddlegameRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOpeningsRoute: AuthenticatedOpeningsRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedPuzzlesRoute: AuthenticatedPuzzlesRoute,
  AuthenticatedTacticsRoute: AuthenticatedTacticsRoute,
  AuthenticatedTrapsRoute: AuthenticatedTrapsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
